namespace Academics.DataModel
{
    public class CourseRequestModel
    {
        //  public int CourseId { get; set; }  //Auto-generated by the database, not needed in request model
        public string Name { get; set; } = string.Empty; // e.g., "Mathematics"
        public string Code { get; set; } = string.Empty; // CBSE subject code
        public int MaxMarks { get; set; } = 100;
        //public ICollection<AssessmentRequestModel> Assessments { get; set; } = new List<AssessmentRequestModel>();
    }
}
